package tr.com.cetinkaya.handterminal.helpers;

import java.io.Serializable;

import tr.com.cetinkaya.handterminal.R;

public enum BarkodTipi implements Serializable {
    BARKODSUZ_KIRMIZI_INDIRIM,
    BARKODLU_KIRMIZI_INDIRIM,
    BARKODSUZ_BEYAZ,
    BARKODLU_BEYAZ,
    BARKODSUZ_TAKSITLI_FIYAT,
    BARKODLU_TAKSITLI_FIYAT,
    INDIRIMLI_RAF,
    INDIRIMSIZ_RAF,
    ZUCCACIYE_RAF,
    BARKODSUZ_KIRMIZI_TAKSITLI_FIYAT,
    BARKODLU_KIRMIZI_TAKSITLI_FIYAT,
    BARKODSUZ_KIRMIZI_50,
    BARKODLU_KIRMIZI_50,
    BARKODSUZ_KIRMIZI_TAKSITLI_50,
    BARKODLU_KIRMIZI_TAKSITLI_50,
    DIKEY_BARKODLU_BEYAZ,
    DIKEY_BARKODLU_KIRMIZI_INDIRIM,
}
